### ISSUE TITLE
How can I make the data persistent on the disk?

### ISSUE THREAD

**Issue by mbx2015** [kwart/ldap-server#2]
Hello, 
Thanks for this ldap server,

I'm working on an ldap server than can be used as plugin based on your ldap server, I would like to know how can I store the data on disk permanently (not in-memory)?

**Comment by kwart** [comment]
Check the ApacheDS API. . Mainly the partition types could be interesting (`org.apache.directory.server.core.api.partition.Partition` implementations).

AFAIK, the default ApacheDS behavior is to store into filesystem. I just needed the quick LDAP start for testing, therefor I use the in-memory implementations instead of the default .

**Comment by mbx2015** [comment]
I'm so confused, I can't find where the the Partition stores data, only schema and system folders that I can find in the Temp directory, But when I connect to the server I can get all partitions.
Can you help me on this plz, I need to store the data on disk and get it back when I restart the server.

Thanks in advance.

**Comment by kwart** [comment]
Try to ask in ApacheDS users list. (http://directory.apache.org/mailing-lists-and-irc.html)
